---
# module: rd-ansible-grafana-install/tasks/configure
# description: Configure rd-ansible-grafana-install

- name: Change grafana port
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: 'http_port ='
    line: "http_port = {{ grafana_port }}"
  notify: restart_grafana

- name: Flush handlers so we can load up new config if required
  meta: flush_handlers

- name: Add datasource
  uri:
    url: "http://127.0.0.1:{{ grafana_port }}/api/datasources"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body: { "name":"InfluxDB","type":"influxdb","url":"{{ influx_db_endpoints[0] }}","password":"{{ influx_db_password }}","user":"{{ influx_db_user }}","database":"telegraf","basicAuth":false,"isDefault":true,"access":"proxy" }
    body_format: json
    status_code: [ 200, 409 ]
  register: datasource_output

- debug: var=datasource_output
